import sqlite3
import json

conn = sqlite3.connect("database.sqlite")

cursor = conn.cursor()

# TURN ON FOREIGN KEY CONSTRAINTS
cursor.execute("PRAGMA foreign_keys = ON")

# insert into skillVideos
delete_query = """DELETE FROM skillVideos WHERE 1"""
cursor.execute(delete_query)
insert_skillVideos_query = """
INSERT INTO 
    skillVideos (id, contributor_id, title, link)
VALUES
    (0, 0, "How to Make Boiled Water", "watch?v=7_j5S38m3wY"),
    (2, 2, "How to Cook Perfect Quinoa", "watch?v=czVXWq_qCyk"),
    (3, 3, "Mastering Knife Skills - Dicing Technique", "watch?v=veE0E79dEEc"),
    -- GastroLabFood youtube channel
    (4, 4, "How to Cook Button Mushrooms", "watch?v=NpCtLNmp_nw"),
    (5, 5, "How to Poach an Egg", "watch?v=mth4vZBWiMY"),
    (6, 6, "How to Clean Shrimps", "watch?v=TPaekJ8Itf0"),
    (7, 7, "How to Clean Squid", "watch?v=bw0M8wYsyRM"),
    (8, 8, "How to Cut Leeks", "watch?v=VyvmBcg8KmY"),
    (9, 0, "How to Prepare Asparagus", "watch?v=N66jT42VWFw"),
    (10, 0, "How to Cut Shallots", "watch?v=JL02Lx-9GPk"),
    (11, 0, "How to Peel Garlic", "watch?v=tzV28_eGC0Q"),
    (12, 0, "How to Cook Scallops", "watch?v=ZZiFjt_ZPIc"),
    (13, 0, "How to Deseed a Pomegranate", "watch?v=1AMijG8RwEk"),
    (14, 0, "How to Parboil Tomatoes", "watch?v=30bwbsB1_cM"),
    (15, 0, "How to Separate An Egg White from the Yolk", "watch?v=daGhiEmcLSw"),
    (16, 0, "How to Fillet Fish - Way 1", "watch?v=q_DJYPYYenU"),
    (17, 0, "How to Saute Vegetables", "watch?v=aw_rqgMkzOw"),
    (18, 0, "How to Fillet Fish - Way 2", "watch?v=l7_lf937CIM"),
    (19, 0, "How to Reduce the Bitterness of Eggplants", "watch?v=4H6Qrgkk2e8"),
    (20, 0, "How to Make Flavoured Melted Butter", "watch?v=cpkZ3cMSbn0"),
    (21, 0, "How to Boil Brocolli", "watch?v=QoJdKkJbDRU"),
    (22, 0, "How to Dry Lettuce", "watch?v=HmsnPa9f0kc"),
    (23, 0, "How to Peel and Cut Oranges", "watch?v=LuLEJmu_heI"),
    (24, 0, "How to Prepare Dried Mushrooms", "watch?v=dyMYOkHviEY"),
    (25, 0, "How to Make Citrus Fruits Easier to Squeeze", "watch?v=XxKv-IApgHQ"),
    (26, 1, "How to Tie a Roast With a String", "watch?v=ND53rqGd28s"),
    (27, 1, "How to Cut Tomatoes", "watch?v=2wEesa3jMiM"),
    (28, 1, "How to Mince Walnuts", "watch?v=dpEtwVUU0KY"),
    (29, 1, "How to Melt Chocolate", "watch?v=CQJp-ZqMvBE"),
    (30, 1, "How to Cook Roasted Garlic", "watch?v=t9B3zKWs7cU"),
    (31, 1, "How to Caramelise Onions", "watch?v=Nh7V3Qj-9lU"),
    (32, 1, "How to Clean Chicken Legs from Joints", "watch?v=-1sj9uFZsyA"),
    (33, 1, "How to Peel and Chop Hazelnuts", "watch?v=UHHYf33oqig"),
    (34, 1, "How to Peel Avocado", "watch?v=6etDV96Tjbw"),
    (35, 1, "How to Cut Fennel", "watch?v=gtGYWZLskCo"),
    (36, 1, "How to Carve a Turkey", "watch?v=w-AgOnli4Hc"),
    (37, 1, "How to Stuff a Turkey", "watch?v=voWVwYOpLyw"),
    (38, 1, "How to Cook Classic Sweet Shortcrust Pastry", "watch?v=c91hBdZbnwQ"),
    -- cookingguide youtube channel
    (39, 2, "How to Clean Artichokes", "watch?v=rAF3o5rITy8"),
    (40, 2, "How to Slice Apples", "watch?v=65p7wk-hgEQ"),
    (41, 2, "How to Cut Zucchinis", "watch?v=6pjLeHMWnS4"),
    (42, 2, "How to Mash Bananas", "watch?v=EfmQfQWK7SU"),
    (43, 2, "How to Crack Eggs", "watch?v=PF7dKy7FNtg"),
    (44, 2, "How to Beat Eggs", "watch?v=3H8hxFlCcCQ"),
    (45, 2, "How to Peel Peaches", "watch?v=NO4t5oA-EUM"),
    (46, 2, "How to Chop Rosemary", "watch?v=c80C0hSxa2Y"),
    (47, 2, "How to Use a Cooking String", "watch?v=gGDjT0zPM10"),
    (48, 2, "How to Use a Colander", "watch?v=wdLA40yskjg"),
    (49, 2, "How to Chop Italian Parsely", "watch?v=xpBT9v8GAF8"),
    (50, 3, "How to Pick Bananas", "watch?v=yMByZrRbU68"),
    (51, 3, "How to Chop Apples", "watch?v=yacwMfbxssw"),
    (52, 3, "How to Pick Blueberries", "watch?v=4sgOglJPXL4"),
    (53, 3, "How to Pick Italian Parsely", "watch?v=676tQLenltw"),
    (54, 3, "How to Use a Deboner", "watch?v=AwCmx5yUCQk"),
    (55, 3, "How to Peel Pineapples", "watch?v=D1dQ0h-X5YU"),
    (56, 3, "How to Use a Bread Knife", "watch?v=GjArbq8xDWc"),
    (57, 3, "How to Core Pineapples", "watch?v=NBrBzzwxHgI"),
    (58, 3, "How to Slice Red Pears", "watch?v=TkDafHALFVg"),
    (59, 3, "How to Use a Bamboo Steamer", "watch?v=U_RkcOof098"),
    (60, 3, "How to Core Apples", "watch?v=ZIvr9Ex59ug"),
    (61, 3, "How to Pick Thyme", "watch?v=_IWtr4bUlrM"),
    (62, 3, "How to Dice Zucchini", "watch?v=byb91Ju0UJw"),
    (63, 3, "How to Broil Seafood", "watch?v=dI8op-WFQvM"),
    (64, 3, "How to Make Whipped Cream", "watch?v=f2fFcjwvTWs"),
    (65, 3, "How to Slice Pineapples", "watch?v=jbd6iqS89oM"),
    (66, 3, "How to Cube Turnips", "watch?v=lkXqH_BqIfU"),
    (67, 4, "How to Whip Egg Whites", "watch?v=pbbH_jlqlBk"),
    (68, 4, "How to Use a Cleaver Knife", "watch?v=rT6vSieNcC0"),
    (69, 4, "How to Grate Ginger Root", "watch?v=-abiTYqbPQM"),
    (70, 4, "How to Peel Tomatoes", "watch?v=1GQ0r-5ufC4"),
    (71, 4, "How to Pick Ginger Root", "watch?v=6TQfU1J8fN8"),
    (72, 4, "How to Slice Turnips", "watch?v=AbLWARpORLs"),
    (73, 4, "How to Poach Seafood", "watch?v=IYRN0MEX_xg"),
    (74, 4, "How to Pick Lemongrass", "watch?v=K43dkE7M4iE"),
    (75, 4, "How to Flambe", "watch?v=Lq4GjyCisbI"),
    (76, 4, "How to Pick Turnips", "watch?v=VT2EGiZhcqw"),
    (77, 4, "How to Pick and Types Tofu", "watch?v=_YDgOf-s4ho"),
    (78, 4, "How to Halve a Banana", "watch?v=dWv6LC_0uSw"),
    (79, 5, "How to Slice Tofu", "watch?v=e9VyoziVC7c"),
    (80, 5, "How to Pick Blackberries", "watch?v=mPPO7Zv421U"),
    (81, 5, "How to Thaw Fish", "watch?v=qGChFQyYTDo"),
    (82, 5, "How to Bake Seafood", "watch?v=DYi5_vXrz6o"),
    (83, 5, "How to Clean Turnips", "watch?v=c9wFgwOeb9o"),
    (84, 5, "How to Clean Ginger Root", "watch?v=jkowzIV2QqI"),
    (85, 5, "How to Pan Fry Bacon", "watch?v=n3f4GOEv7ck"),
    (86, 5, "How to Marinate Tofu", "watch?v=yPh81Q9DgZA"),
    (87, 5, "How to Use a Deep Fryer", "watch?v=-7zDfKNEkmY"),
    (88, 5, "How to Select a Whole Chicken", "watch?v=1_NuuC2uMBo"),
    (89, 5, "How to Pick Calamari", "watch?v=2z1E1sILbVg"),
    (90, 5, "How to Pick Pork Tenderloin", "watch?v=3BGaZl9DpCo"),
    (91, 5, "How to Dice Capsicum", "watch?v=3hULyHM3cGo"),
    (92, 5, "How to Sear Chicken", "watch?v=4IJorho8zGc"),
    (93, 5, "How to Use Chicken Safely", "watch?v=4pCI8BIVvfk"),
    (94, 5, "How to Clean Capsicum", "watch?v=5oxepN3X89U"),
    (95, 5, "How to Chop Hazelnuts", "watch?v=BbYa3Bu0VWk"),
    (96, 6, "How to Pick Octopus", "watch?v=CBrvIUamD0o"),
    (97, 6, "How to Microwave Bacon", "watch?v=FQi2-EvpNiw"),
    (98, 6, "How to Chop Walnuts", "watch?v=HAUtd6atcr8"),
    (99, 6, "How to Baste Ham", "watch?v=IbyHWarJ8vQ"),
    (100, 6, "How to Pick Hazelnuts", "watch?v=Kb-sG39ckFs"),
    (101, 6, "How to Pick Bok Choy", "watch?v=LEvyc_0-VeY"),
    (102, 6, "How to Trim Fat from Pork Tenderloin", "watch?v=LFVYcfyd_S8"),
    (103, 6, "How to Clean Bok Choy", "watch?v=LLZTvu9N_DU"),
    (104, 6, "How to Chop Chestnus", "watch?v=MGS21XX3X7c"),
    (105, 6, "How to Pick Ham", "watch?v=Ml53GhNt6hg"),
    (106, 6, "How to Butterfly Chicken Breast", "watch?v=Ot46Cueod4s"),
    (107, 6, "How to Clean Broccoli", "watch?v=Q2kZAEU5RRU"),
    (108, 6, "How to Pan Fry Chicken", "watch?v=QFZ-OaiB3nY"),
    (109, 6, "How to Chop Peacans", "watch?v=QWyBkwzsE6g"),
    (110, 6, "How to Pick Mussels", "watch?v=SQZMMTOGeOI"),
    (111, 6, "How to Pick Pecans", "watch?v=T6TEBglwJh0"),
    (112, 6, "How to Broil Chicken Thighs", "watch?v=V3nTtHja8JQ"),
    (113, 6, "How to Use a Cheese Slicer", "watch?v=VO5SRS5DTO8"),
    (114, 6, "How to Pick Pistachio Nuts", "watch?v=WbxkXGkl7QY"),
    (115, 6, "How to Make Al Dente Pasta", "watch?v=ZuQcQOSXpe0"),
    (116, 6, "How to Pick Bacon", "watch?v=_h1j8yIayuI"),
    (117, 6, "How to Pick Pine Nuts", "watch?v=axCT96sGwnA"),
    (118, 7, "How to Sear Pork Tenderloin", "watch?v=gweiQjiaUPk"),
    (119, 7, "How to Pick Macadamia Nuts", "watch?v=i_Ls5pi7pP0"),
    (120, 7, "How to Quarter a Whole Chicken", "watch?v=id92bIP9Wm4"),
    (121, 7, "How to Cook Safely With Fish", "watch?v=jSkJlDAzWVg"),
    (122, 7, "How to Pick Broccoli", "watch?v=juKP3khVF78"),
    (123, 7, "How to Chop Macadamia Nuts", "watch?v=oHW_tUsw2zQ"),
    (124, 7, "How to Chop Peanuts", "watch?v=omy0L_U82xs"),
    (125, 7, "How to Cook Cous Cous", "watch?v=osywU2_1fAk"),
    (126, 7, "How to Cool White Rice", "watch?v=oxsJXH-VKmg"),
    (127, 7, "How to Roast Capsicum", "watch?v=rQ1_HJtRmO0"),
    (128, 7, "How to Pick Peanuts", "watch?v=yJbn5rbUGp8"),
    (129, 7, "How to Slice Strawberries", "watch?v=OvAHmLw5e5Q"),
    (130, 7, "How to Pick Cashews", "watch?v=STi0bt3SBjM"),
    (131, 7, "How to Slice Thai Chilli Peppers", "watch?v=ZIcnGkovCvY"),
    (132, 7, "How to Oven Roast Chicken", "watch?v=czGlKhaqMQ8"),
    (133, 7, "How to Pick Walnuts", "watch?v=g8voWo7V8B4"),
    (134, 7, "How to Clean White Button Mushrooms", "watch?v=jGyZVAuCL54"),
    (135, 7, "How to Chop Brazil Nuts", "watch?v=vJ5modStrn4"),
    (136, 7, "How to Pick Chestnuts", "watch?v=01cYXYmipUY"),
    (137, 7, "How to Dice Jalapeno Peppers", "watch?v=0dbpF2BghI0"),
    (138, 8, "How to Pick Clams", "watch?v=3mxnA38Xqhw"),
    (139, 8, "How to Clean Watermelons", "watch?v=3wYFJLap3dU"),
    (140, 8, "How to Steam Clams", "watch?v=4IScX7YvnqU"),
    (141, 8, "How to Use a Dry Measuring Cup", "watch?v=7gFLl6SR9Ys"),
    (142, 8, "How to Cross Brussel Sprouts", "watch?v=ADHJkGY7qXM"),
    (143, 8, "How to Steep Chamomile", "watch?v=EgQ63WD4nRA"),
    (144, 8, "How to Bread Products", "watch?v=EzF6Eaga8Pw"),
    (145, 8, "How to Pick Strawberries", "watch?v=FEdGrbDhZBo"),
    (146, 8, "How to Slice Starfruits", "watch?v=Hcgv0smgSXg"),
    (147, 8, "How to Prepare Calamari", "watch?v=IREOfCKkSu4"),
    (148, 8, "How to Pick Raspberries", "watch?v=JVzGkRl8df8"),
    (149, 8, "How to Use Parchment Paper", "watch?v=Jz4Lr9jGKkk"),
    (150, 8, "How to Use a Measuring Sppon", "watch?v=NdNRZL304gg"),
    (151, 8, "How to Clean Green Cabbage", "watch?v=O74sngXTumk"),
    (152, 8, "How to Pick Shitake Mushrooms", "watch?v=P0V01pXu3vY"),
    (153, 8, "How to Pick Almonds", "watch?v=QRdBrAwnVnM"),
    (154, 8, "How to Pick Brussel Sprouts", "watch?v=Rxz_iyHt7NY"),
    (155, 9, "How to Cube Watermelons", "watch?v=VJ_nRtuX3Mw"),
    (156, 9, "How to Use a Liquid Measuring Cup", "watch?v=XvYTYREiFZU"),
    (157, 9, "How to Chop Cashews", "watch?v=Y-VpXlrn-uM"),
    (158, 9, "How to Chop Strawberries", "watch?v=ZYiXRX6Fmdc"),
    (159, 9, "How to Chop Almonds", "watch?v=_AxlGCTlmGc"),
    (160, 9, "How to Select Veal", "watch?v=cq4v-pwy91w"),
    (161, 9, "How to Use a Flavour Injector", "watch?v=dRQuW4eizM0"),
    (162, 9, "How to Make Oven Toasted Almonds", "watch?v=eWMdUSudgrA"),
    (163, 9, "How to Slice Watermelons", "watch?v=gCsgTNillW4"),
    (164, 9, "How to Slice Green Cabbage", "watch?v=iTXx6NLKlTY"),
    (165, 9, "How to Fan Strawberries", "watch?v=mma4wgX22wg"),
    (166, 9, "How to Clean Brussel Sprouts", "watch?v=q3dvqyHSAEA"),
    (167, 9, "How to Use an Immersion Blender", "watch?v=t9GmitshuZg"),
    (168, 9, "How to Use a Hand Mixer", "watch?v=tMPIkdO_3SY"),
    (169, 9, "How to Pick Parsely", "watch?v=-kvHYerNVqg"),
    (170, 9, "How to Cube Pineapples", "watch?v=1OB-XqLTntY"),
    (171, 9, "How to Use a Ladle", "watch?v=3AZ6tKJhKgg"),
    (172, 9, "How to Use a Paring Knife", "watch?v=7dieSXpQdEo"),
    (173, 9, "How to Steam Vegetables", "watch?v=AOOh9SyKhc4"),
    (174, 9, "How to Pick Eggs", "watch?v=Bw8YTe4aXKY"),
    (175, 9, "How to Clean Zucchini", "watch?v=E3U1zKfLyNQ"),
    (176, 9, "How to Use a Zester", "watch?v=HfEqvpFF0F8"),
    (177, 10, "How to Pit Plums", "watch?v=HyNVL8nQCTw"),
    (178, 10, "How to Use a Rolling Pin", "watch?v=JPc9sEHUNes"),
    (179, 10, "How to Boil Crab Legs", "watch?v=NlmTOFjtPpQ"),
    (180, 10, "How to Use a Garlic Press", "watch?v=Qud3NrN7fDY"),
    (181, 10, "How to Slice Zucchini", "watch?v=RoqP1J0Y6AY"),
    (182, 10, "How to Pick Chipotle Peppers", "watch?v=VVVQRNl6-os"),
    (183, 10, "How to Saute in a Wok", "watch?v=ZV0V9bc31U8"),
    (184, 10, "How to Pick Oregano", "watch?v=au6Ki6FpyDY"),
    (185, 10, "How to Cube Plums", "watch?v=bIne0PO8cq4"),
    (186, 10, "How to Soft Boil Eggs", "watch?v=cCPR3l_iEgA"),
    (187, 10, "How to Flip Food in a Wok", "watch?v=cNaiCF5fmM4"),
    (188, 10, "How to Use a Pan", "watch?v=dNHjY3cxbSI"),
    (189, 10, "How to Pick Watermelons", "watch?v=e-yKAmyyOPc"),
    (190, 10, "How to Use an Iron Skillet", "watch?v=f3MvWRFKTZY"),
    (191, 10, "How to Use a Stand Mixer", "watch?v=pkTe65K7o90"),
    (192, 10, "How to Use a Lemon Press", "watch?v=u3HfFW8oFe8"),
    (193, 10, "How to Use a Masher", "watch?v=zY_412Mp4Xs"),
    (194, 10, "How to Shave Parmesan Cheese", "watch?v=zuKODO8tLZM"),
    (195, 10, "How to Pick Cinnamon", "watch?v=3605Pg2vrP4"),
    (196, 10, "How to Boil Spinach", "watch?v=7Sy1ZgmmZc8"),
    (197, 10, "How to Use a Stock Pot", "watch?v=8kDCuWqK7JI"),
    (198, 11, "How to Use a Strainer", "watch?v=9qq3TyElMwo"),
    (199, 11, "How to Use Kitchen Scissors", "watch?v=J5I9wAQoizM"),
    (200, 11, "How to Pick Artichokes", "watch?v=N7hsggFsESk"),
    (201, 11, "How to Clean Portobello Mushrooms", "watch?v=RQr_EdvnyQg"),
    (202, 11, "How to Clean White Asparagus", "watch?v=U-qlxcbw56Y"),
    (203, 11, "How to Cut Beef Against Grain", "watch?v=YOnkygi99Pg"),
    (204, 11, "How to Use a Spatula", "watch?v=Z4l9UYphgDY"),
    (205, 11, "How to Grate Cinnamon", "watch?v=e32Rv6WnU-E"),
    (206, 11, "How to Pan Fry", "watch?v=fLxvuFj7r2Q"),
    (207, 11, "How to Use a Steak Knife", "watch?v=fxSzH73AMVk"),
    (208, 11, "How to Soften Butter", "watch?v=olUyDOsCNMs"),
    (209, 11, "How to Clean Artichokes", "watch?v=rAF3o5rITy8"),
    (210, 11, "How to Boil Artichokes", "watch?v=rqCxJN1FumQ"),
    (211, 11, "How to Pick Apples", "watch?v=gk1u8nDtpo8"),
    (212, 11, "How to Shred Cheddar Cheese", "watch?v=nRyf4VWEsDY"),
    (213, 11, "How to Slice Avocados", "watch?v=0LqJdMxZras"),
    (214, 11, "How to Saute Onions", "watch?v=2NKDdgHLp8U"),
    (215, 11, "How to Peel Carrots", "watch?v=4LRZ5-GbUOU"),
    (216, 12, "How to Use a Steamer", "watch?v=5wdDqjqDn80"),
    (217, 12, "How to Dice Shallots", "watch?v=9bgacGJsmpU"),
    (218, 12, "How to Saute Vegetables", "watch?v=AEUzh49ZiSM"),
    (219, 12, "How to Prepare Watercress", "watch?v=CPzqkQ8-6SY"),
    (220, 12, "How to Dice Avocados", "watch?v=CYx6lO0suuU"),
    (221, 12, "How to Pit Avocados", "watch?v=F6jHrCgwcwg"),
    (222, 12, "How to Pick Asparagus", "watch?v=G5wYzz06FLw"),
    (223, 12, "How to Peel Apples", "watch?v=GFZ2SEhD5DY"),
    (224, 12, "How to Clean Raddishes", "watch?v=HlLWIXrDhr8"),
    (225, 12, "How to Check Doneness When Baking", "watch?v=ILVLKeMImiw"),
    (226, 12, "How to Clean Carrots", "watch?v=JSL2ETSU9QY"),
    (227, 12, "How to Chop Mint", "watch?v=O4xuBMWPF_w"),
    (228, 12, "How to Clean Cauliflower", "watch?v=Qj90HckZbdQ"),
    (229, 12, "How to Use a Vegetable Peeler", "watch?v=RcS6SbX-0Bg"),
    (230, 12, "How to Chop Chocolate", "watch?v=Sco8k6FmBLY"),
    (231, 12, "How to Use a Whisk", "watch?v=UuajCIKaVGE"),
    (232, 12, "How to Slice Rhubarb", "watch?v=VSdwivdjxzk"),
    (233, 12, "How to Pick Chives", "watch?v=W8Y6AKg6Bto"),
    (234, 12, "How to Deep Fry Tofu", "watch?v=XUv5mZk832s"),
    (235, 12, "How to Pan Fry Tofu", "watch?v=XiJlWncaLLI"),
    (236, 13, "How to Pick Bay Leaves", "watch?v=aoM4gungTv4"),
    (237, 13, "How to Use a Wok", "watch?v=c-hD20fatdM"),
    (238, 13, "How to Chop Chives", "watch?v=fUBdCoby-20"),
    (239, 13, "How to Use Tongs", "watch?v=gNdKUJt_3ts"),
    (240, 13, "How to Sift Flour", "watch?v=rWRHKX-9C6c"),
    (241, 13, "How to Boil Beets", "watch?v=rcUWky400UM"),
    (242, 13, "How to Prepare Spaghetti Squash", "watch?v=sD-4E_woLz0"),
    (243, 13, "How to Pick Bean Sprouts", "watch?v=sDmh5fqjaIA"),
    (244, 13, "How to Slice Mozzarella Cheese", "watch?v=umDlYLAgxVM"),
    (245, 13, "How to Sweat Onions", "watch?v=vK0zLJy3hnY"),
    (246, 13, "How to Slice Radishes", "watch?v=wdNcXafZFJ4"),
    (247, 13, "How to Pick Salmon", "watch?v=0YIg_gZCAas"),
    (248, 13, "How to Slice Fennel", "watch?v=1q05rz0_uUA"),
    (249, 13, "How to Pick Bone in Ribeye", "watch?v=3GUgi1bF6ow"),
    (250, 13, "How to Prepare Butternut Squash", "watch?v=3qwTjTUMT8Y"),
    (251, 13, "How to Peel Pears", "watch?v=46v6oMSOfi0"),
    (252, 13, "How to Blanch Green Beans", "watch?v=AYHPPa2H8yM"),
    (253, 13, "How to Pick Sun Dried Tomatoes", "watch?v=BV8gDHHSRRg"),
    (254, 13, "How to Pick Red Snapper", "watch?v=G0T0XBDj8qw"),
    (255, 13, "How to Pick Sugar Snap Peas", "watch?v=GgYFN3tUthg"),
    (256, 13, "How to Shred Carrots", "watch?v=NEKiIzfxFvc"),
    (257, 13, "How to Pick Alfalfa Sprouts", "watch?v=WLqc4Q3ZuS4"),
    (258, 14, "How to Pick Basil", "watch?v=XXcCfeLjmDs"),
    (259, 14, "How to Clean Green Beans", "watch?v=c-tzXjBQ2tU"),
    (260, 14, "How to Slice White Potatoes", "watch?v=hg1gQPRGyrM"),
    (261, 14, "How to Clean Celery", "watch?v=k_7DOLxvrbM"),
    (262, 14, "How to Pan Fry Tempeh", "watch?v=l-_yLgqa-YQ"),
    (263, 14, "How to Make an Icing Bag", "watch?v=lHHv22G8ixo"),
    (264, 14, "How to Caramelize Sugar", "watch?v=pIOBaqKkCi8"),
    (265, 14, "How to Sear Tuna Steak", "watch?v=qXBfYYF-BGA"),
    (266, 14, "How to Core Pears", "watch?v=r3gPZ7gY6jA"),
    (267, 15, "How to Pick Snap Peas", "watch?v=w0D-cqychuU"),
    (268, 15, "How to Shred Iceberg Lettuce", "watch?v=NQ7uk3aOxtE"),
    (269, 15, "How to Scramble Eggs", "watch?v=_8BJZetE9rg"),
    (270, 15, "How to Poach Eggs", "watch?v=d9XTJ9-_n0Q"),
    (271, 15, "How to Grill a Hamburger", "watch?v=hME_epnyrYM"),
    (272, 15, "How to Peel White Potatoes", "watch?v=qeD7LJKwauw"),
    (273, 15, "How to Pick Spinach", "watch?v=CorR1aCpf3A"),
    (274, 15, "How to Pick Purple Eggplant", "watch?v=MwFfU4ZODu4"),
    (275, 15, "How to Boil Edamame (Soy Beans)", "watch?v=_gfc_EQ-lOQ"),
    (276, 15, "How to Flip Eggs", "watch?v=3DriNZTCXxQ"),
    (277, 15, "How to Brown Butter", "watch?v=CBiByrMgCMc"),
    (278, 15, "How to Slice Leek", "watch?v=Dz-igwuwhFc"),
    (279, 15, "How to Clarify Butter", "watch?v=FPHXZTYi2Ow"),
    (280, 15, "How to Grill Sirloin", "watch?v=KFH9y-bAz4M"),
    (281, 16, "How to Slice Sweet Potatoes", "watch?v=LYOofLe64IA"),
    (282, 16, "How to Grill Tofu", "watch?v=VeVG2OPw6aw"),
    (283, 16, "How to Pick Ribeye Steaks", "watch?v=XMZZbhmWetk"),
    (284, 16, "How to Boil Eggs", "watch?v=a9fVMm3bHYs"),
    (285, 16, "How to Fry Eggs", "watch?v=j2C-bp7I1jU"),
    (286, 16, "How to Pick Green Leaf Lettuce", "watch?v=kiKJzHyP5Yo"),
    (287, 16, "How to Peel Sweet Potatoes", "watch?v=oB6h3DscMUw"),
    (288, 16, "How to Clean Iceberg Lettuce", "watch?v=tAxuaJyPqhA"),
    (289, 16, "How to Punch Out Dough", "watch?v=8InH3VJP71E"),
    (290, 16, "How to Pick Cherry Tomatoes", "watch?v=G7ZXu8Sea9k"),
    (291, 16, "How to Mince Garlic", "watch?v=HFPhXM6TtI4"),
    (292, 17, "How to Pick Tuna Steak", "watch?v=JsD3dwdYjGM"),
    (293, 17, "How to Knead Dought", "watch?v=KvCAteRyhAQ"),
    (294, 17, "How to Prepare Potstickers for Cooking", "watch?v=NsE294KL8EY"),
    (295, 17, "How to Use the Grill Lid Properly", "watch?v=Yt0Vze7UITs"),
    (296, 17, "How to Simmer Water", "watch?v=e_hKjQXvA1Q"),
    (297, 17, "How to Melt Chocolate", "watch?v=g1076D4xR84"),
    (298, 17, "How to Grill Onions", "watch?v=gsZK6BTnk3k"),
    (299, 17, "How to How to Use a Meat Thermometer", "watch?v=iTwRyl_rj6s"),
    (300, 17, "How to Pick Garlic", "watch?v=01w1cacfiS0"),
    (301, 17, "How to Remove Kernels from Corn", "watch?v=0KZcl4D63gk"),
    (302, 17, "How to Pick Prawns", "watch?v=3iJQB94kuNQ"),
    (303, 17, "How to Use Oil When Grilling", "watch?v=7P0YYT2JtlY"),
    (304, 17, "How to Brown Ground Beef", "watch?v=ACW08JyDuVg"),
    (305, 17, "How to Steam Vegetables", "watch?v=ASasVFiKF1M"),
    (306, 17, "How to Grill Potatoes", "watch?v=AnmkJJBHSw4"),
    (307, 17, "How to Press Garlic", "watch?v=C5-LGqwPnhY"),
    (308, 17, "How to Pick Green Onions", "watch?v=CA-HgJQMmJg"),
    (309, 17, "How to Grill Corn", "watch?v=CHijvLqiub4"),
    (310, 18, "How to Slice Cucumbers", "watch?v=Ep8qi0yQ7wE"),
    (311, 18, "How to Pick Kale", "watch?v=MWD0I-NZZ5o"),
    (312, 18, "How to Remove Fat from Pork Chops", "watch?v=Q5myb1MFfWA"),
    (313, 18, "How to Slice Chinese Eggplant", "watch?v=W4NARYbsEtI"),
    (314, 18, "How to Slice Tomatoes", "watch?v=YlkC80JFyds"),
    (315, 18, "How to Break Down a Lobster", "watch?v=alFmgjE5wvk"),
    (316, 18, "How to Pour Pancake Batter", "watch?v=bf49gfkamMY"),
    (317, 18, "How to Slice Green Onions", "watch?v=dcdhaxl54pY"),
    (318, 18, "How to Tie Roast Meat", "watch?v=hpEvYqmynuM"),
    (319, 18, "How to Pick Cucumbers", "watch?v=ito9_Qx-W14"),
    (320, 18, "How to Grill Safely", "watch?v=l0rjakMlfFA"),
    (321, 18, "How to Fold Omelets", "watch?v=n9YZZR0y128"),
    (322, 18, "How to Roast Meat", "watch?v=pWBnpU7Y7Qw"),
    (323, 18, "How to Crush Garlic", "watch?v=uoYYX_SpV7I"),
    (324, 18, "How to Flip Pancakes", "watch?v=yCbhuGyFev4"),
    (325, 18, "How to Slice Cucumbers", "watch?v=yLMduj1YfoY"),
    (326, 18, "How to Prepare Kale", "watch?v=yX9d9OPmtB8"),
    (327, 18, "How to Grill Zuchinni", "watch?v=zE3ht4tWGwo"),
    (328, 18, "How to Mince Red Onions", "watch?v=0ZONIYnX03k"),
    (329, 19, "How to Boil Tripe", "watch?v=4auPt4nf984"),
    (330, 19, "How to Boil Beef Tongue", "watch?v=4egkJdL8WWE"),
    (331, 19, "How to Sear Beef", "watch?v=AKN-UZV9atE"),
    (332, 19, "How to Pick Corn", "watch?v=Am_KLxhZkG0"),
    (333, 19, "How to Pick Lamb Chops", "watch?v=BalNsWI1sCQ"),
    (334, 19, "How to Grill Fish", "watch?v=CxKq3FUvXeI"),
    (335, 19, "How to Marinade Chicken", "watch?v=Gh2I_4VojmI"),
    (336, 19, "How to Slice Garlic", "watch?v=HOKxWHPmVKY"),
    (337, 19, "How to Blanch Vegetables", "watch?v=ZzEDraqcqMw"),
    (338, 19, "How to Dice Red Onions", "watch?v=mZCuba7tBZI"),
    (339, 19, "How to Peel Garlic", "watch?v=rEJbfJlkfCs"),
    (340, 19, "How to Pick Cucumbers", "watch?v=vetqiH05Q90"),
    (341, 19, "How to Peel Grapes", "watch?v=-ZP0PD6caJE"),
    (342, 19, "How to Toast Macadamia Nuts", "watch?v=W4RA4t7pvCU"),
    (343, 19, "How to Freeze Strawberries", "watch?v=a64JJgEL6es"),
    (344, 19, "How to Roast Pumpkin Seeds", "watch?v=loGdPINQ93E")
"""
cursor.execute(insert_skillVideos_query)
conn.commit()


# insert into skillVideoInRecipe
delete_query = """DELETE FROM skillVideoInRecipe WHERE 1"""
cursor.execute(delete_query)
insert_skillVideoInRecipe_query = """
INSERT INTO 
    skillVideoInRecipe (recipe_id, skill_video_id)
VALUES
    (0, 281),
    (0, 2),
    (1, 105),
    (2, 222),
    (2, 9),
    (2, 153)
"""
cursor.execute(insert_skillVideoInRecipe_query)
conn.commit()

# insert into skillVideoSaves
delete_query = """DELETE FROM skillVideoSaves WHERE 1"""
cursor.execute(delete_query)

insert_skillVideoSaves_query = """
INSERT INTO 
    skillVideoSaves(ruser_id, skill_video_id)
VALUES
    (0, 2),
    (0, 5),
    (0, 3),
    (0, 105),
    (0, 222),
    (0, 9),
    (0, 153)
"""
cursor.execute(insert_skillVideoSaves_query)
conn.commit()

cursor.close()